package com.rancho_smart.ms_inventario_ventas.entity;

public enum Moneda {
    PESO_COLOMBIANO,
    DOLAR_ESTADOUNIDENSE,
    PESO_MEXICANO,
    PESO_ARGENTINO,
    REAL_BRASILENO,
    PESO_CHILENO,
    PESO_URUGUAYO,
    SOL_PERUANO,
    BOLIVAR_VENEZOLANO,
    GUARANI_PARAGUAYO,
    QUETZAL_GUATEMALTECO,
    DOLAR_CANADIENSE,
    CORDOBA_NICARAGUENSE,
    COLON_COSTARRICENSE,
    BALBOA_PANAMENO,
    LEMPIRA_HONDURENO,
    DOLAR_BELICEÑO,
    EURO,
    LIBRA_ESTERLINA,
    YEN_JAPONES,
    FRANCO_SUIZO
}
